### ISSUE TITLE
Fonts are messed up in code blocks

### ISSUE THREAD

**Issue by jonnybarnes** [alexwilson/frontend#2384]
Text directly in the code element gets the rule:
```css
code[class*="language-"], pre[class*="language-"] {
	word-wrap: normal;
	background: none;
	color: #f8f8f2;
	font-family: Consolas,Monaco,Andale Mono,Ubuntu Mono,monospace;
	font-size: 1em;
	-webkit-hyphens: none;
	hyphens: none;
	line-height: 1.5;
	tab-size: 4;
	text-align: left;
	text-shadow: 0 1px rgba(0,0,0,.3);
	white-space: pre;
	word-break: normal;
	word-spacing: normal;
}
```

But then specific tokens such as `<span class="token function">setItem</span>` get a more specific rule applied to them:
```css
* {
	font-family: Avenir Next,Avenir,Arial,sans-serif;
}
```

So the code block gets rendered like so:
<img width="789" alt="image" src="https://github.com/alexwilson/frontend/assets/108303/71fe0bd3-2275-4dbe-9f5e-c006467e30d3">
